---
abstract: 'Korean spellchecker'
author:
  - 'C.H. Kang <chahkang@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100922'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-KoreanSpeller
recommends: {}
requires:
  Any::Moose: 0
  Encode: 0
  LWP::UserAgent: 0
  namespace::autoclean: 0
  utf8: 0
version: 0.002
